### ISSUE TITLE
Creation of PIT over a LINK and LINK-Satellite fails

### ISSUE THREAD

**Issue by jabibo** [ScalefreeCOM/datavault4coalesce#7]
datavault4coalesce-Version: 1.0.1
Reproduce: Creation of PIT over a LINK and LINK-Satellite 
Error: Link-Definition is not been found (empty) in INSERT-Statement

 

![bug](https://github.com/ScalefreeCOM/datavault4coalesce/assets/57133231/581b1f79-6002-494b-803e-79e88209c40d)

**Comment by tkirschke** [comment]
Hi @jabibo and thanks for reaching out!

I looked into this and am able to reproduce the described error. Your suggested fix worked for me, and I implemented it in the linked branch. 

**But** another problem occured when the LEFT JOIN to the Link Satellite should be created, but is not. 
After some investigation, I noticed that this is also the case for Hub Satellites. In both cases, the background node template looks for columns with the attribute "is_hk", which should be set by the *ColumnDropdownSelector* that sets the Hashkey inside a Satellite V0 & V1. But apperently this DropdownSelector does not set this attribute properly right now. 

I have reported this problem to Coalesce and will let you know here as soon as I got feedback from them! 

In case you don't already use the new Satellite Nodes, where the new ColumnDropdownSelector is used, the linked branch should already work for you!

Best regards
Tim
