### ISSUE TITLE
Ghost-Records are not being created for TIMESTAMP_NTZ(9)

### ISSUE THREAD

**Issue by jabibo** [ScalefreeCOM/datavault4coalesce#9]
In the function ghost_record_per_datatype the ghost records are created with consideration of the datatypes in the target-table.
However in our dataset timestamps are of type TIMESTAMP_NTZ(9). This is not in the list ..
Additionaly in our table there is a not-null-constraint..this creates an issue

![image](https://github.com/ScalefreeCOM/datavault4coalesce/assets/57133231/2aa5763a-fb1a-418c-9ed5-6bf69eb15c5e)
 Version is 1.0.1

**Comment by tkirschke** [comment]
Hi @jabibo and thanks for reaching out!

I have modified the ghost_record_per_datatype to catch all datatypes that start with "DATE" or "TIMESTAMP". I tried it with a column having the datatype "TIMESTAMP_NTZ(9)" and it worked like a charm. 

> Additionaly in our table there is a not-null-constraint..this creates an issue.

This should no longer be a problem now!

The modified code can be found in the attached branch. Please check if this version works for you as well and solves the issue. If so, I will happily merge it into main!

Best regards
Tim

**Comment by jabibo** [comment]
..mach mal Feierabend 😳

Von Unterwegs gesendet

Am 10.08.2023 um 19:50 schrieb Tim Kirschke ***@***.***>:

﻿

Hi @jabibo<https://github.com/jabibo> and thanks for reaching out!

I have modified the ghost_record_per_datatype to catch all datatypes that start with "DATE" or "TIMESTAMP". I tried it with a column having the datatype "TIMESTAMP_NTZ(9)" and it worked like a charm.

Additionaly in our table there is a not-null-constraint..this creates an issue.

This should no longer be a problem now!

The modified code can be found in the attached branch. Please check if this version works for you as well and solves the issue. If so, I will happily merge it into main!

Best regards
Tim
